const state={user:null,exams:[],results:[],performance:null,stats:null};
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function dt(v){if(!v)return "-";const d=new Date(v);return Number.isNaN(d.getTime())?"-":d.toLocaleString(undefined,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"});}
async function api(url,opt={}){const r=await fetch(url,{credentials:"include",...opt});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x.message||"Request failed.");return x;}
async function auth(){const x=await api("/api/me");if(!x.loggedIn||!x.user){location.href="/loginPrem.html";return false;}if(x.user.role&&x.user.role!=="teacher"){location.href="/student-dashboard.html";return false;}state.user=x.user;document.querySelectorAll("[data-user-name]").forEach(e=>e.textContent=x.user.fullname||"Teacher");return true;}
async function load(){state.exams=(await api("/api/teacher/exams")).exams||[];state.results=(await api("/api/teacher/results")).results||[];state.performance=await api("/api/teacher/performance");state.stats=await api("/api/teacher/dashboard");render();}
async function logout(){await fetch("/api/logout",{method:"POST",credentials:"include"}).catch(()=>{});location.href="/loginPrem.html";}
function startRealtime(){load().catch(console.error);setInterval(()=>load().catch(console.error),5000);}

function render(){document.getElementById("kpis").innerHTML=`<div class="portal-kpi"><span>Total Exams</span><strong>${state.stats.totalExams}</strong></div><div class="portal-kpi"><span>Published</span><strong>${state.stats.publishedExams}</strong></div><div class="portal-kpi"><span>Students</span><strong>${state.stats.totalStudents}</strong></div><div class="portal-kpi"><span>Average Score</span><strong>${Number(state.stats.averageScore||0).toFixed(1)}%</strong></div>`;const g=document.getElementById("grid");const a=state.performance?.byExam||[];g.innerHTML=a.length?a.map(x=>`<article class="portal-card"><h2>${esc(x.exam)}</h2><div class="meta"><div><span>Submissions</span><strong>${x.attempts}</strong></div><div><span>Average</span><strong>${x.average}%</strong></div><div><span>Status</span><strong>Live</strong></div></div></article>`).join(""):`<div class="portal-empty">Student submissions will appear here as exams are completed.</div>`;}
document.addEventListener("DOMContentLoaded",async()=>{if(await auth())startRealtime();});
